package com.cidra.hologram_beta.common

object TagList {

    val categoryName = listOf<String>(
        "Game",
        "ゲーム",
        "Sing",
        "歌枠",
        "LIVE",
        "LIVE",
        "Chat",
        "雑談",
        "Birthday",
        "生誕祭",
        "Original Song",
        "オリジナル曲",
        "Drawing",
        "お絵かき",
        "Watch Along",
        "同時視聴",
        "Cover",
        "歌ってみた",
        "ASMR"
    )

    val nameToId = mutableMapOf(
        "ときのそら" to "UCp6993wxpyDPHUpavwDFqgg",
        "AZKi" to "UC0TXe_LYZ4scaW2XMyi5_kw",
        "ロボ子" to "UCDqI2jOz0weumE8s7paEk6g",
        "さくらみこ" to "UC-hM6YJuNYVAmUWxeIr9FeA",
        "白上フブキ" to "UCdn5BQ06XqgXoAxIhbqw5Rg",
        "夏色まつり" to "UCQ0UDLQCjY0rmuxCDE38FGg",
        "夜空メル" to "UCD8HOxPs4Xvsm8H0ZxXGiBw",
        "赤井はあと" to "UC1CfXB_kRs3C-zaeTG3oGyg",
        "アキ・ローゼンタール" to "UCFTLzh12_nrtzqBPsTCqenA",
        "湊あくあ" to "UC1opHUrw8rvnsadT-iGp7Cg",
        "癒月ちょこ" to "UCp3tgHXw_HI0QMk1K8qh3gQ",
        "百鬼あやめ" to "UC7fk0CB07ly8oSl0aqKkqFg",
        "紫咲シオン" to "UCXTpFs_3PqI41qX2d9tL2Rw",
        "大空スバル" to "UCvzGlP9oQwU--Y0r9id_jnA",
        "大神ミオ" to "UCp-5t9SrOQwXMU7iIjQfARg",
        "猫又おかゆ" to "UCvaTdHTWBGv3MKj3KVqJVCw",
        "戌神ころね" to "UChAnqc_AY5_I3Px5dig3X1Q",
        "不知火フレア" to "UCvInZx9h3jC2JzsIzoOebWg",
        "白銀ノエル" to "UCdyqAaZDKHXg4Ahi7VENThQ",
        "宝鐘マリン" to "UCCzUftO8KOVkV4wQG1vkUvg",
        "兎田ぺこら" to "UC1DCedRgGHBdm81E1llLhOQ",
        "潤羽るしあ" to "UCl_gCybOJRIgOXw6Qb4qJzQ",
        "星街すいせい" to "UC5CwaMl1eIgY8h02uZw7u8A",
        "天音かなた" to "UCZlDXzGoo7d44bwdNObFacg",
        "桐生ココ" to "UCS9uQI-jC3DE0L4IpXyvr6w",
        "角巻わため" to "UCqm3BQLlJfvkTsX_hvm0UmA",
        "常闇トワ" to "UC1uv2Oq6kNxgATlCiez59hw",
        "姫森ルーナ" to "UCa9Y57gfeY0Zro_noHRVrnw",
        "雪花ラミィ" to "UCFKOVgVbGmX65RxO3EtH3iw",
        "桃鈴ねね" to "UCAWSyEs_Io8MtpY3m-zqILA",
        "獅白ぼたん" to "UCUKD-uaobj9jiqB-VXt71mA",
        "尾丸ポルカ" to "UCK9V2B22uJYu3N7eR_BT9QA",
        "ラプラス・ダークネス" to "UCENwRMx5Yh42zWpzURebzTw",
        "鷹嶺ルイ" to "UCs9_O1tRPMQTHQ-N_L6FU2g",
        "博衣こより" to "UC6eWCld0KwmyHFbAqK3V-Rw",
        "沙花叉クロヱ" to "UCIBY1ollUsauvVi4hW4cumw",
        "風真いろは" to "UC_vMYWcDjmfdpH6r4TTn1MQ",
        "Iofi" to "UCAoy6rzhSf4ydcYjJw3WoVg",
        "Moona" to "UCP0BspO_AMEe3aQqqpo89Dg",
        "Risu" to "UCOyYb1c43VlX9rc_lT6NKQw",
        "Ollie" to "UCYz_5n-uDuChHtLo7My1HnQ",
        "Anya" to "UC727SQYUvx5pDDGQpTICNWg",
        "Reine" to "UChgTyjG-pdNvxxhdsXfHQ5Q",
        "Calliope" to "UCL_qhgtOy0dy1Agp8vkySQg",
        "Kiara" to "UCHsx4Hqa-1ORjQTh9TYDhww",
        "Ina'nis" to "UCMwGHR0BTZuLsmjY_NT5Pwg",
        "Gura" to "UCoSrY_IQQVpmIRZ9Xf-y93g",
        "Amelia" to "UCyl1z3jo3XHR1riLFKG5UAg",
        "IRyS" to "UC8rcEBzJSleTkf_-agPM20g",
        "Sana" to "UCsUj0dszADCGbF3gNrQEuSQ",
        "Fauna" to "UCO_aKKYxn4tvrqPjcTzZ6EQ",
        "Kronii" to "UCmbs8T6MWqUHP1tIQvSgKrg",
        "Mumei" to "UC3n5uGu18FoCy23ggWWp8tA",
        "Baelz" to "UCgmPnx-EEeOrZSg5Tiw7ZRQ",
        "花咲みやび" to "UC6t3-_N8A6ME1JShZHHqOMw",
        "奏手イヅル" to "UCZgOv3YDEs-ZnZWDYVwJdmA",
        "アルランデ" to "UCKeAhJvy8zgXWbh9duVjIaQ",
        "律可" to "UC9mf_ZVpouoILRY9NUIaK-w",
        "アステル" to "UCNVEsYbiZjH5QLmGeSgTSzg",
        "岸堂天真" to "UCGNI4MENvnsymYjKiZwv9eg",
        "夕刻ロベル" to "UCANDOlYTJT7N5jlRC3zfzVA",
        "影山シエン" to "UChSvpZYRPh0FvG4SJGSga3g",
        "荒咬オウガ" to "UCwL7dgTxKo8Y4RFIKWaf8gA",
        "Hololive Official" to "UCJFZiqLMntJufDCHc6bQixg"
    )
}